# Generated by Django 4.1 on 2022-08-26 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="is_seller",
            field=models.BooleanField(default=False),
        ),
    ]
