version: "3.9"

services:
  db:
    container_name: db_m5_sprint_5
    image: postgres:14
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s
    volumes:
      - postgres_m5_sprint_5:/var/lib/postgresql/data

volumes:
  postgres_m5_sprint_5:
    driver: local
